### ISSUE TITLE
Is it possible to use it locally and have user profiles?

### ISSUE THREAD

**Issue by ChromaPIE** [auxves/disco-generator#1]
First I want to thank you for the mod and the generator. The one and only choice for creating custom discs on Fabric 1.19.

The generator is super useful. It would be better if it's a program cuz if it's running on the browser the profile can't be saved, if I want to create a single huge add-on I have to keep the site open, otherwise everything needs to be done once again.

It's totally okay if it will not be worked on. Not very many ppl is using the mod and the generator and I don't deserve a feature that's only request by myself but I'll still do it.

**Comment by auxves** [comment]
I'm not going to make a desktop app for this, but I am currently adding support for saving and loading drafts on the web version.

**Comment by ChromaPIE** [comment]
Should be enough for what I actually need. Appreciate it!

**Comment by auxves** [comment]
I just pushed the update :) you can now save drafts and load them at a later time.

**Comment by ChromaPIE** [comment]
> I just pushed the update :) you can now save drafts and load them at a later time.

Sounds great but it actually won't save drafts. When I click the button, Load Saved Draft doesn't show anything but No saved drafts! Refreshing the page clears everything as before.

Edit: Did more test and found that drafts can only be saved when no disc is added. That means you can only save drafts that contains nothing but Name, Identifier and Description, adding discs will prevent drafts from saving.

**Comment by auxves** [comment]
I fixed it and added some notifications too :) let me know if there are any more issues.

**Comment by ChromaPIE** [comment]
Things are working just fine now. Thanks for all that!
